@startuml
skin rose
skinparam ActivityFontSize 15
skinparam ArrowFontSize 12
start
:Input field is empty;
if () then ([up or down arrow key pressed])
    :Retrieves previousCommand
    from CommandHistory
    if available;
    :previousCommand fills Input field;
else ([else])
    :User enters command in Input field;
endif
:User executes command;
:Command saved in CommandHistory;
:Input field is cleared;

stop
@enduml
