@startuml
!include style.puml
skinparam ArrowFontStyle plain

box UI UI_COLOR_T1
participant ":CommandBox" as Model UI_COLOR
participant ":CommandHistory" as ModelCH UI_COLOR
end box

[-> Model : keyPress(e)
activate Model

Model -> Model : handleKeyPressEvent(e)
Model -> Model : handleArrowKeyPress(e)
activate Model
Model -> ModelCH : getInstance()
activate ModelCH
ModelCH --> Model :
deactivate ModelCH

Model -> ModelCH : getCommandHistory(direction)
activate ModelCH

ModelCH --> Model : previousCommand
deactivate ModelCH

Model -> Model : setText(previousCommand)

[<-- Model
deactivate Model

@enduml
