@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor LOGIC_COLOR_T4
skinparam classBackgroundColor LOGIC_COLOR

package Logic as LogicPackage {
    package "Parser Classes" as ParserClasses{
    }

    Class "<<interface>>\nLogic" as Logic
    Class LogicManager

    package "Command Classes" as CommandPackage {
        package "Commands Utility Classes" as CommandsUtil {
        }
        Class XYZCommand
        Class CommandResult
        Class "{abstract}\nCommand" as Command
        note right of XYZCommand: XYZCommand = AddPersonCommand, \nFindPersonCommand, etc
        XYZCommand -up-|> Command
        XYZCommand .down.> CommandsUtil
        Command .> CommandResult : creates >
    }

    LogicManager .up|> Logic
    LogicManager -up> ParserClasses
    LogicManager ..> Command : calls >
    LogicManager ..> CommandResult
    ParserClasses .down> XYZCommand : creates >
    Logic ..> CommandResult
}

package Model {
    class HiddenModel #FFFFFF
}

package Storage {
    class HiddenModel #FFFFFF
}

Class HiddenOutside #FFFFFF
HiddenOutside .down.> Logic

LogicManager -down-> Model
LogicManager -right> Storage
Command .right.> Model

@enduml
